spring:
  data:
    redis:
      port: 6379
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  session:
    store-type: redis
    timeout: 7d
  mongodb:
    uri: ${MONGO_URI}
logging:
  level:
    org.springframework.boot.context.config: DEBUG
iana:
  base-url: ${IANA_BASE_URL}
hostinger:
  api:
    token: ${HOSTINGER_API_TOKEN}