spring:
  application:
    name: domain_finder
  mongodb:
      uri: ${URI_MONGO}
      database: domain_finder
  data:
    redis:
      url: ${REDIS_URI}
logging:
  level:
    org.springframework.boot.context.config: DEBUG